name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
  
    - name:  build
      working-directory: /
      run: cpp main.cpp -o compiled_Hello_World
    
